// Сброс пользовательских данных
d_geo_tools_update_user_date:dialog{label="Сброс пользовательских данных";
:toggle{label="Виды профиля";key="basement-in-profile";value="0";}
:toggle{label="Стандартные строки подвала профиля";key="profile-standart-str";value="0";}
:toggle{label="Настройки пересечек профилей";key="intersection-lines-list";value="0";}
:toggle{label="Пользовательские форматы в менедж.форматов";key="USER";value="0";}
:toggle{label="Шаблон чертежа";key="template";value="0";}
ok_cancel;
}