(defun get-point-list-AO (nome-AO / )
  (cond
    ((eq nome-AO "¬¿Œ")
     
     )
    ((eq nome-AO "«¿Œ")
     
     )
    ((eq nome-AO "—¿Œ")
     
     )
    ((eq nome-AO "—¬¿Œ")
     
     )
    ((eq nome-AO "—«¿Œ")
     
     )
    ((eq nome-AO "÷¿Œ")
     
     )
    ((eq nome-AO "ﬁ¿Œ")
     
     )
    ((eq nome-AO "ﬁ¬¿Œ")
     
     )
    ((eq nome-AO "ﬁ«¿Œ")
     
     )
    (T
     nil)
    )
  )